/**
 * Generate exactly one characterization test per applied fix.
 *
 * "One test per fix" is a hard requirement, and the honest version of it is a
 * test that would fail if THAT fix had damaged the module. So each generated
 * case is anchored to the exported symbol enclosing the finding: if the fix
 * deleted the function it was inside, or changed its signature, the case named
 * after that fix is the one that goes red.
 *
 * The surface is read from the source BEFORE the fix, because that is the
 * behaviour being characterized. Reading it afterwards would assert whatever
 * the codemod did, which is not a test.
 */
import { apiFor } from './core.mjs';
import { staticSurface } from './templates/characterization.mjs';

const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

/** The exported function or class whose body contains `line`. */
export function enclosingExport(j, root, line) {
  let best = null;
  let bestSpan = Infinity;
  // A declaration wrapped in `export` carries no loc of its own — recast puts
  // it on the ExportNamedDeclaration. Without this fallback every exported
  // function looks like it spans nothing, enclosingExport always returns null,
  // and every generated case degrades to the same module-level assertion.
  const consider = (name, node, fallback) => {
    const loc = (node && node.loc) || fallback;
    if (!loc) return;
    const { start, end } = loc;
    if (start.line > line || end.line < line) return;
    const span = end.line - start.line;
    if (span < bestSpan) { best = name; bestSpan = span; }
  };
  root.find(j.ExportNamedDeclaration).forEach((p) => {
    const d = p.node.declaration;
    if (!d) return;
    const wrapper = p.node.loc;
    if (d.type === 'VariableDeclaration') {
      d.declarations.forEach((dec) => {
        if (dec.id.type === 'Identifier') consider(dec.id.name, dec.init || dec, wrapper);
      });
    } else if (d.id) {
      consider(d.id.name, d, wrapper);
    }
  });
  return best;
}

/**
 * @param {string} originalSource  the file as it was BEFORE any fix
 * @param {string} filePath
 * @param {Array<{rule:string,line:number,fixer:string,reason:string}>} fixes
 */
export function renderTestsForFile(originalSource, filePath, fixes, importPath) {
  const j = apiFor(filePath);
  const root = j(originalSource);
  const surface = staticSurface(j, root);
  if (surface.length === 0) return null; // nothing exported: nothing to characterize

  const names = surface.map((s) => s.name).sort();
  const byName = new Map(surface.map((s) => [s.name, s]));

  const l = [
    `import { describe, it, expect } from 'vitest';`,
    `import * as mod from ${q(importPath)};`,
    ``,
    `// GENERATED by the remediation run — one case per applied fix.`,
    `//`,
    `// These characterize ${filePath} as it was before remediation. They do not`,
    `// assert the code smells are gone; they assert the module still presents`,
    `// the surface it did, which is what a fix that deleted the wrong line`,
    `// would break.`,
    `describe(${q(`${filePath} (characterized before remediation)`)}, () => {`,
    `  it('exports the same names it did before remediation', () => {`,
    `    expect(Object.keys(mod).sort()).toEqual(${JSON.stringify(names)});`,
    `  });`,
    ``
  ];

  for (const fix of fixes) {
    const owner = enclosingExport(j, root, fix.line);
    const label = `${fix.fixer} at line ${fix.line} (${fix.rule})`;
    l.push(`  it(${q(`survives ${label}`)}, () => {`);
    if (owner && byName.has(owner)) {
      const s = byName.get(owner);
      l.push(`    expect(mod.${owner}).toBeDefined();`);
      if (s.kind === 'function') {
        l.push(`    expect(typeof mod.${owner}).toBe('function');`);
        l.push(`    expect(mod.${owner}.length).toBe(${s.arity});`);
      } else if (s.kind === 'class') {
        l.push(`    expect(typeof mod.${owner}).toBe('function');`);
      }
    } else {
      // Module-scope fix: the whole surface is what it could have damaged.
      l.push(`    expect(Object.keys(mod).sort()).toEqual(${JSON.stringify(names)});`);
    }
    l.push(`  });`, ``);
  }

  l.push(`});`, ``);
  return l.join('\n');
}

/** Where a generated test has to live for each workspace's runner to find it. */
export function testPathFor(filePath) {
  const base = filePath.split('/').pop().replace(/\.(js|mjs|cjs|ts|tsx)$/, '');
  if (filePath.startsWith('api/')) {
    return { path: `api/test/${base}.generated.test.js`, importPath: relativeImport(`api/test`, filePath) };
  }
  if (filePath.startsWith('web/')) {
    const dir = filePath.split('/').slice(0, -1).join('/');
    return { path: `${dir}/${base}.generated.spec.ts`, importPath: `./${base}` };
  }
  return null;
}

function relativeImport(fromDir, target) {
  const from = fromDir.split('/');
  const to = target.split('/');
  while (from.length && to.length && from[0] === to[0]) { from.shift(); to.shift(); }
  const up = from.map(() => '..');
  return [...up, ...to].join('/').replace(/^(?!\.)/, './');
}
