#!/usr/bin/env bash
# Prove the API contracts in docs/research/api-contracts.md against the live services.
#
# Reads credentials from the environment. Never prints them. Writes findings to
# docs/research/api-contracts-verified.md, which is what closes the research ticket.
#
#   export SONAR_TOKEN_READ=...      # SonarQube Cloud token
#   export SONAR_ORG=...             # e.g. phix
#   export SONAR_PROJECT_KEY=...     # e.g. phix_sonar-sandbox-app
#   export JIRA_BASE_URL=https://yoursite.atlassian.net
#   export JIRA_USER_EMAIL=...
#   export JIRA_API_TOKEN=...
#   export JIRA_PROJECT_KEY=...      # e.g. APP
#
#   ./scripts/verify-api-contracts.sh
#
# Read-only except for one Jira probe issue, which it creates and then tells you
# how to delete. Nothing is written to Sonar.

set -uo pipefail

OUT="docs/research/api-contracts-verified.md"
PASS=0; FAIL=0; SKIP=0

ok()   { printf '  \033[32mPASS\033[0m %s\n' "$1"; PASS=$((PASS+1)); echo "- **PASS** $1" >> "$OUT"; }
bad()  { printf '  \033[31mFAIL\033[0m %s\n' "$1"; FAIL=$((FAIL+1)); echo "- **FAIL** $1" >> "$OUT"; }
skip() { printf '  \033[33mSKIP\033[0m %s\n' "$1"; SKIP=$((SKIP+1)); echo "- **SKIP** $1" >> "$OUT"; }
sect() { printf '\n\033[1m%s\033[0m\n' "$1"; echo -e "\n## $1\n" >> "$OUT"; }

# Returns 0 (true) when one or more vars are MISSING, so `if need X; then skip; fi` reads naturally.
need() {
  local missing=1
  for v in "$@"; do
    if [ -z "${!v:-}" ]; then printf '\033[33mmissing env: %s\033[0m\n' "$v"; missing=0; fi
  done
  return $missing
}

command -v jq >/dev/null || { echo "jq is required"; exit 1; }

# Load credentials without being handed them: Keychain first, then .env.
# Anything already exported in the environment wins over both.
_here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [ -x "$_here/scripts/secrets.sh" ] && command -v security >/dev/null 2>&1; then
  eval "$("$_here/scripts/secrets.sh" export 2>/dev/null || true)"
fi
if [ -f "$_here/.env" ]; then
  set -a; . "$_here/.env"; set +a
fi

mkdir -p "$(dirname "$OUT")"
{
  echo "# API contract verification — live results"
  echo
  echo "Generated by \`scripts/verify-api-contracts.sh\`. Settles the UNVERIFIED items in"
  echo "[api-contracts.md](api-contracts.md) against the real services."
  echo
  echo "**Run at:** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$OUT"

# ---------------------------------------------------------------- SonarQube Cloud
sect "SonarQube Cloud"

if need SONAR_TOKEN_READ SONAR_ORG SONAR_PROJECT_KEY; then
  skip "Sonar checks — set SONAR_TOKEN_READ, SONAR_ORG, SONAR_PROJECT_KEY"
else
  SB="https://sonarcloud.io/api"
  SH=(-s -H "Authorization: Bearer ${SONAR_TOKEN_READ}")

  # Auth reachable?
  auth=$(curl "${SH[@]}" "$SB/authentication/validate")
  if [ "$(echo "$auth" | jq -r '.valid // false')" = "true" ]; then
    ok "token authenticates (\`/api/authentication/validate\` → valid:true)"
  else
    bad "token did not validate — every Sonar check below is unreliable"
  fi

  # Issue search, scoped to code smells (both taxonomies, see doc §2)
  raw=$(curl "${SH[@]}" -G "$SB/issues/search" \
        --data-urlencode "componentKeys=${SONAR_PROJECT_KEY}" \
        --data-urlencode "organization=${SONAR_ORG}" \
        --data-urlencode "resolved=false" \
        --data-urlencode "ps=500")

  if echo "$raw" | jq -e '.issues' >/dev/null 2>&1; then
    total=$(echo "$raw" | jq -r '.paging.total // .total // "unknown"')
    got=$(echo "$raw" | jq -r '.issues | length')
    ok "\`/api/issues/search\` returned $got issues (reported total: $total)"
    echo "$raw" > /tmp/sonar-issues-probe.json

    # --- the severity-mode question (doc §3) ---
    legacy=$(echo "$raw" | jq -r '[.issues[] | select(.severity != null)] | length')
    mqr=$(echo "$raw"    | jq -r '[.issues[] | select(.impacts != null and (.impacts|length)>0)] | length')
    echo "- legacy \`severity\` present on: $legacy/$got" >> "$OUT"
    echo "- MQR \`impacts[]\` present on: $mqr/$got" >> "$OUT"
    if [ "$mqr" -gt 0 ] && [ "$legacy" -gt 0 ]; then
      ok "BOTH vocabularies present — pick one deliberately (see ticket #11)"
    elif [ "$mqr" -gt 0 ]; then
      ok "MQR mode: use \`impacts[].severity\` + \`impactSoftwareQualities\`"
    elif [ "$legacy" -gt 0 ]; then
      ok "Standard mode: use \`severity\` + \`types\` (matches the source spec as written)"
    else
      skip "no issues returned — scan the project first, then re-run"
    fi
    { echo; echo "Observed severity values:"; echo '```'
      echo "$raw" | jq -r '[.issues[].severity] | unique | @json' 2>/dev/null
      echo "$raw" | jq -r '[.issues[].impacts[]?.severity] | unique | @json' 2>/dev/null
      echo "$raw" | jq -r '[.issues[].impacts[]?.softwareQuality] | unique | @json' 2>/dev/null
      echo "$raw" | jq -r '[.issues[].type] | unique | @json' 2>/dev/null
      echo '```'; } >> "$OUT"

    # --- hash coverage, for fingerprinting (doc §2) ---
    if [ "$got" -gt 0 ]; then
      h=$(echo "$raw" | jq -r '[.issues[] | select(.hash != null)] | length')
      pct=$(( h * 100 / got ))
      if [ "$pct" -ge 90 ]; then
        ok "\`hash\` present on ${pct}% of issues — safe to fingerprint on it"
      else
        bad "\`hash\` present on only ${pct}% — fingerprint must fall back to line more often than hoped"
      fi
      nl=$(echo "$raw" | jq -r '[.issues[] | select(.line == null)] | length')
      echo "- issues with no \`line\` (file-level): $nl/$got — \`line\` must be optional" >> "$OUT"
      { echo; echo "One real issue, verbatim (redacted of nothing — Sonar issues carry no secrets):"; echo '```json'
        echo "$raw" | jq '.issues[0]'; echo '```'; } >> "$OUT"
    fi
  else
    bad "\`/api/issues/search\` did not return an issues array: $(echo "$raw" | jq -c '.errors // .' | head -c 200)"
  fi

  # Quality gate
  qg=$(curl "${SH[@]}" -G "$SB/qualitygates/project_status" --data-urlencode "projectKey=${SONAR_PROJECT_KEY}")
  st=$(echo "$qg" | jq -r '.projectStatus.status // empty')
  [ -n "$st" ] && ok "quality gate readable → \`$st\`" || bad "quality gate unreadable"

  # Is the read token actually read-only?
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST \
         -H "Authorization: Bearer ${SONAR_TOKEN_READ}" \
         "$SB/project_branches/rename" -d "project=${SONAR_PROJECT_KEY}&name=probe-do-not-apply")
  case "$code" in
    401|403) ok "read token is genuinely read-only (write probe → HTTP $code)" ;;
    400)     skip "write probe → 400: rejected on args before perms; read-only status unproven" ;;
    2*)      bad "read token PERFORMED A WRITE (HTTP $code) — it is not read-only. Reissue it." ;;
    *)       skip "write probe → HTTP $code, inconclusive" ;;
  esac
fi

# ---------------------------------------------------------------------- Jira Cloud
sect "Jira Cloud"

if need JIRA_BASE_URL JIRA_USER_EMAIL JIRA_API_TOKEN JIRA_PROJECT_KEY; then
  skip "Jira checks — set JIRA_BASE_URL, JIRA_USER_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY"
else
  JA=(-s -u "${JIRA_USER_EMAIL}:${JIRA_API_TOKEN}" -H "Content-Type: application/json")
  JB="${JIRA_BASE_URL%/}/rest/api/2"

  me=$(curl "${JA[@]}" "${JIRA_BASE_URL%/}/rest/api/2/myself")
  if echo "$me" | jq -e '.accountId' >/dev/null 2>&1; then
    ok "authenticates as accountId $(echo "$me" | jq -r '.accountId' | cut -c1-8)…"
  else
    bad "Jira auth failed — remaining Jira checks unreliable"
  fi

  # Project visibility. `GET /project` answers 200 [] when unauthenticated, so an
  # empty list is ambiguous, not benign -- call it out rather than sailing past it.
  projs=$(curl "${JA[@]}" "$JB/project")
  pn=$(echo "$projs" | jq -r 'if type=="array" then length else -1 end')
  if [ "$pn" -gt 0 ]; then
    ok "$pn project(s) visible: $(echo "$projs" | jq -r '[.[].key] | join(", ")')"
    if ! echo "$projs" | jq -e --arg k "$JIRA_PROJECT_KEY" 'any(.[]; .key==$k)' >/dev/null; then
      bad "JIRA_PROJECT_KEY='$JIRA_PROJECT_KEY' is NOT among the visible projects -- wrong key or wrong site?"
    fi
  elif [ "$pn" -eq 0 ]; then
    bad "project list is EMPTY. This is what an unauthenticated or wrong-site call looks like (200 + []), not proof the site has no projects. Check JIRA_BASE_URL and that the token's account can see this site."
  else
    bad "unexpected /project response: $(echo "$projs" | jq -c '.' | head -c 160)"
  fi

  # The removed endpoint really removed?
  old=$(curl -s -o /dev/null -w '%{http_code}' -u "${JIRA_USER_EMAIL}:${JIRA_API_TOKEN}" \
        -G "$JB/search" --data-urlencode "jql=project=${JIRA_PROJECT_KEY}")
  if [ "$old" = "410" ]; then
    ok "legacy \`GET /search\` → 410 Gone, exactly as documented"
  else
    skip "legacy \`GET /search\` → HTTP $old (expected 410; do not rely on it either way)"
  fi

  # The replacement
  new=$(curl "${JA[@]}" -X POST "$JB/search/jql" \
        -d "{\"jql\":\"project = ${JIRA_PROJECT_KEY} ORDER BY created DESC\",\"maxResults\":2,\"fields\":[\"key\",\"status\",\"summary\",\"labels\"]}")
  if echo "$new" | jq -e '.issues' >/dev/null 2>&1; then
    ok "\`POST /search/jql\` works"
    has_tok=$(echo "$new" | jq 'has("nextPageToken")')
    has_tot=$(echo "$new" | jq 'has("total")')
    echo "- \`nextPageToken\` present: $has_tok · \`total\` present: $has_tot" >> "$OUT"
    [ "$has_tot" = "false" ] && ok "no \`total\` returned — confirms count-free pagination" \
                             || skip "\`total\` unexpectedly present"
    { echo; echo "Top-level response keys:"; echo '```json'; echo "$new" | jq 'keys'; echo '```'; } >> "$OUT"
  else
    bad "\`POST /search/jql\` failed: $(echo "$new" | jq -c '.errorMessages // .' | head -c 200)"
  fi

  # Project style + real statuses
  proj=$(curl "${JA[@]}" "$JB/project/${JIRA_PROJECT_KEY}")
  style=$(echo "$proj" | jq -r '.style // "unknown"')
  ok "project style: \`$style\` ($([ "$style" = "next-gen" ] && echo "team-managed — statuses addable without site admin" || echo "company-managed — workflow admin needed to add statuses"))"

  sts=$(curl "${JA[@]}" "$JB/project/${JIRA_PROJECT_KEY}/statuses")
  { echo; echo "Statuses actually available:"; echo '```json'
    echo "$sts" | jq -r '[.[] | {type: .name, statuses: [.statuses[].name]}]'; echo '```'; } >> "$OUT"
  n=$(echo "$sts" | jq -r '[.[].statuses[].name] | unique | length')
  if [ "$n" -ge 10 ]; then
    ok "$n statuses available — the full 12-status model may be reachable"
  else
    ok "$n statuses available vs 12 in the source model — compress into labels (doc §5.5)"
  fi

  # Label tolerance + create/transition/comment, via one probe issue
  FP="gf-$(printf '%040x' 0 | tr '0' 'a')"
  body=$(jq -n --arg p "$JIRA_PROJECT_KEY" --arg fp "$FP" '{
    fields:{ project:{key:$p}, issuetype:{name:"Task"},
      summary:"[probe] api contract verification — safe to delete",
      description:"Created by scripts/verify-api-contracts.sh to prove the Jira contract. Delete freely.",
      labels:["sonar-remediation", $fp] }}')
  cr=$(curl "${JA[@]}" -X POST "$JB/issue" -d "$body")
  KEY=$(echo "$cr" | jq -r '.key // empty')

  if [ -n "$KEY" ]; then
    ok "created probe issue \`$KEY\` with a ${#FP}-char fingerprint label (v2, plain-text description)"

    rb=$(curl "${JA[@]}" -X POST "$JB/search/jql" \
         -d "{\"jql\":\"project = ${JIRA_PROJECT_KEY} AND labels = \\\"${FP}\\\"\",\"maxResults\":5,\"fields\":[\"key\"]}")
    if [ "$(echo "$rb" | jq -r '[.issues[].key] | index("'"$KEY"'") // "no"')" != "no" ]; then
      ok "fingerprint-label dedupe lookup round-trips — labels are a viable dedupe key"
    else
      bad "label lookup did NOT find the issue — labels are not a reliable dedupe key here"
    fi

    tr=$(curl "${JA[@]}" "$JB/issue/${KEY}/transitions")
    { echo; echo "Transitions available from the new issue's status:"; echo '```json'
      echo "$tr" | jq -r '[.transitions[] | {id, name, to: .to.name}]'; echo '```'; } >> "$OUT"
    tn=$(echo "$tr" | jq -r '.transitions | length')
    ok "$tn transitions readable by name — match on \`to.name\`, never hardcode ids"

    cm=$(curl "${JA[@]}" -X POST "$JB/issue/${KEY}/comment" -d '{"body":"Plain-text comment via API v2 — proves no ADF needed."}')
    echo "$cm" | jq -e '.id' >/dev/null 2>&1 \
      && ok "v2 accepts a plain-string comment body — ADF genuinely avoidable" \
      || bad "plain-string comment rejected: $(echo "$cm" | jq -c '.errorMessages // .' | head -c 160)"

    { echo; echo "**Probe issue \`$KEY\` was left in place.** Delete it with:"; echo '```bash'
      echo "curl -s -X DELETE -u \"\$JIRA_USER_EMAIL:\$JIRA_API_TOKEN\" \"$JB/issue/$KEY\""; echo '```'; } >> "$OUT"
    printf '\n\033[33mProbe issue %s left in Jira. Deletion command is in %s\033[0m\n' "$KEY" "$OUT"
  else
    bad "could not create probe issue: $(echo "$cr" | jq -c '.errors // .errorMessages // .' | head -c 200)"
  fi
fi

# --------------------------------------------------------------------------- done
sect "Result"
echo "**$PASS passed · $FAIL failed · $SKIP skipped**" >> "$OUT"
printf '\n\033[1m%d passed, %d failed, %d skipped\033[0m\n' "$PASS" "$FAIL" "$SKIP"
printf 'Written to %s\n' "$OUT"
[ "$FAIL" -eq 0 ]
